version: '3.8'

services:
  app:
    image: reminder-bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PG_USER: ${{ vars.PG_USER }}
      PG_PWD: ${{ secrets.PG_PWD }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
