spring:
  application:
    name: reminder-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${PG_USER:postgres}
    password: ${PG_PWD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      auto-commit: false
  jpa:
    show-sql: ${SHOW_SQL:true}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: ${POSTGRES_SCHEMA:reminderbot}
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    default-schema: reminderbot
    change-log: classpath:/liquibase/master.yml
    database-change-log-table: _databasechangelog
    database-change-log-lock-table: _databasechangeloglock
bot:
  name: "NvdReminderBot"
  token: ${BOT_TOKEN}