name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build Docker image
        run: docker build -t telegram-bot .

      - name: docker-compose-down
        run: docker-compose down

      - name: docker-compose-pull
        run: docker-compose pull

      - name: docker-compose-up
        run: docker-compose up -d